theme: jekyll-theme-leap-day
title: React ND Project 3 - Mobile Flashcards
description: Project Notes by James Priest
# google_analytics: UA-121627234-7

exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules/,
  Gruntfile.js,
  package-lock.json,
  package.json,
  src/
]